version: '2'

services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/.docker/postgres/data:/var/lib/postgresql/data
    networks:
      server:
        ipv4_address: 10.5.0.2

  web:
    build: .
    working_dir: /videoshare
    container_name: web
    tty: true
    stdin_open: true
    volumes:
      - .:/videoshare
    ports:
      - 3000:3000
    environment:
      - RAILS_ENV=development
    networks:
      server:
        ipv4_address: 10.5.0.3

networks:
  server:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/28
