version: '2'

services:
  postgres:
    image: postgres:9.5
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ~/.docker/postgres/data:/var/lib/postgresql/data
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

networks:
  vpcbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1